export const SET_TIME = "SET_TIME"
export const SET_PRICES = "SET_PRICES"
export const PIN_PRICE = "PIN_PRICE"
export const UNPIN_PRICE = "UNPIN_PRICE"
export const SET_CONTACT = "SET_CONTACT"
export const SET_RESERVE_TYPE = "SET_RESERVE_TYPE"